#!/usr/bin/env bash
#
# set up the ImageMagick environment and run whatever was given in the argument list

export MAGICK_HOME=$HOME/ImageMagick/ImageMagick-6.8.1
export PATH="$PATH:$MAGICK_HOME/bin"
#export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib"


echo "Running: $@"
eval "$@"
