#!/usr/bin/env bash
#
# Script to get disk usage from the network drive status web page, and then
# plot out various user and server usages.

PY_HOME="$HOME/etc/python/common"

# Mine the web page, and load results into HDF5 file.
$PY_HOME/GetDiskUsage.py

# Plot various servers and user pie charts from HDF5 file
ServerList=" \
  Tasman \
  Avalanche \
  Blizzard \
  Squall \
  DendHome \
  DendUser1 \
  DendUser2 \
  DendUser3 \
  PermaFrost \
  CloudSeed \
  Icicle \
  SharedHome"

UserList=" \
  Minnie \
  Jennie \
  Leah \
  Peter \
  Aryeh \
  Sean \
  Ben \
  Stacey \
  SteveS \
  SteveH \
  Sue \
  Adele \
  Matt \
  Rachel \
  Clay \
  Amanda \
  Other"

for Server in $ServerList
do
  $PY_HOME/PlotDiskUsage.py Server $Server
done

for User in $UserList
do
  $PY_HOME/PlotDiskUsage.py User $User
done
