function powerspectraplot(x1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Aug-2017 10:52:12
[pow1, w] = spectrum(x1);
w =w / 2; %denormalize the frequency
per = 1./w; % convert to period
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create loglog
loglog(per,pow1(:,1)),;

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[2 256]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XDir','reverse','XScale','log','YScale','log');
xlabel('period, hours');

