#
# Config
#

DEST = $(HOME)/etc/matlab
SCRIPTS = $(DEST)/PlotTseriesSet.m \
          $(DEST)/ContourfLogScale.m

#
# Targets
#

all: $(SCRIPTS)

#$(DEST)/%.m: %.m
#	cp $(<) $(@)

$(DEST)/%.m: %.m
	@echo "$(<) is now obsolete"

