#!/usr/bin/env perl
#
# Script to run gen_adv on a list of simulation cases
#

BEGIN { push(@INC, "$ENV{HOME}/etc/perl"); }

use strict;
use File::Basename;
use DiagUtils;

#######################################################################
# SUBROUTINES
#######################################################################

#######################################################################
# MAIN
#######################################################################

my $ConfigFile;
my $Nprocs;

my $Config;

my @CaseList;
my $Case;

my %AdvectJobs;
my $Aname;
my $Zmin;
my $Zmax;
my @FileList;
my $FileSpec;
my $ifile;

my @AdvectCmds;
my $icmd;

my @SysArgs;
my $iarg;

my $ilog;
my $LogFile;
my $Pid;

if ($#ARGV != 1)
  {
  print "ERROR: must supply exactly two arguments\n";
  print "\n";
  print "USAGE: run_azavg <ConfigFile> <NumberProcesses>\n";
  exit -1;
  }

$ConfigFile = $ARGV[0];
$Nprocs = $ARGV[1];

print "Run azavg diagnostic jobs\n";
print "  Configuration file: $ConfigFile\n";
print "  Number of processes: $Nprocs\n";
print "\n";

# Read in info from the config file.
($Config) = &DiagUtils::ReadDiagConfigFile($ConfigFile);

# Walk through all cases and all azavg jobs and construct the
# corresponding list of azavg commands. 
#
# Divide the total number of azavg commands evenly by the 
# requested number of processes and run each subset in
# separate processes.

@CaseList = @{ $$Config{CASE_LIST} };
%AdvectJobs = %{ $$Config{ADVECT} };

foreach $Case (@CaseList)
  {
  foreach $Aname (sort(keys(%AdvectJobs)))
    {
    # Grab the job specs
    $Zmin       = $AdvectJobs{$Aname}{ZMIN};
    $Zmax       = $AdvectJobs{$Aname}{ZMAX};
    @FileList   = @{ $AdvectJobs{$Aname}{FILE_LIST} };

    $iarg = 0;
    undef @SysArgs;
    $SysArgs[$iarg++] = "gen_adv"; 
    $SysArgs[$iarg++] = "-z";
    $SysArgs[$iarg++] = "$Zmin:$Zmax";
    foreach $ifile (0 .. $#FileList)
      {
      $FileSpec = $FileList[$ifile];
      $FileSpec =~ s/<CASE>/$Case/g;
      $SysArgs[$iarg++] = $FileSpec;
      }

    # Add the command line to the main list
    $AdvectCmds[$icmd++] = [ @SysArgs ];
    }
  }

# Submit the jobs
&DiagUtils::SubmitParallelJobs(\@AdvectCmds, $Nprocs, "advect");

exit 0;
