#!/usr/bin/env perl
#
# Script to run tsavg on a list of simulation cases
#

BEGIN { push(@INC, "$ENV{HOME}/etc/perl"); }

use strict;
use File::Basename;
use DiagUtils;

#######################################################################
# SUBROUTINES
#######################################################################

#######################################################################
# MAIN
#######################################################################

my $ConfigFile;
my $Nprocs;

my $Config;

my @CaseList;
my $Case;

my %TsavgJobs;
my $Tname;
my $AvgFunc;
my $SubSmotion;
my @FileList;
my $FileSpec;
my $ifile;

my @TsavgCmds;
my $icmd;

my @SysArgs;
my $iarg;

if ($#ARGV != 1)
  {
  print "ERROR: must supply exactly two arguments\n";
  print "\n";
  print "USAGE: run_tsavg <ConfigFile> <NumberProcesses>\n";
  exit -1;
  }

$ConfigFile = $ARGV[0];
$Nprocs = $ARGV[1];

print "Run tsavg diagnostic jobs\n";
print "  Configuration file: $ConfigFile\n";
print "  Number of processes: $Nprocs\n";
print "\n";

# Read in info from the config file.
($Config) = &DiagUtils::ReadDiagConfigFile($ConfigFile);

# Walk through all cases and all tsavg jobs and construct the
# corresponding list of tsavg commands. 
#
# Divide the total number of tsavg commands evenly by the 
# requested number of processes and run each subset in
# separate processes.

@CaseList = @{ $$Config{CASE_LIST} };
%TsavgJobs = %{ $$Config{TSAVG} };

foreach $Case (@CaseList)
  {
  foreach $Tname (sort(keys(%TsavgJobs)))
    {
    # Grab the job specs
    $AvgFunc    = $TsavgJobs{$Tname}{AVG_FUNC};
    $SubSmotion = $TsavgJobs{$Tname}{SUB_SMOTION};
    @FileList   = @{ $TsavgJobs{$Tname}{FILE_LIST} };

    $iarg = 0;
    undef @SysArgs;
    $SysArgs[$iarg++] = "tsavg"; 
    if ($SubSmotion =~ /[Yy][Ee][Ss]/)
      {
      $SysArgs[$iarg++] = "-m";
      }
    $SysArgs[$iarg++] = $AvgFunc;
    foreach $ifile (0 .. $#FileList)
      {
      $FileSpec = $FileList[$ifile];
      $FileSpec =~ s/<CASE>/$Case/g;
      $SysArgs[$iarg++] = $FileSpec;
      }

    # Add the command line to the main list
    $TsavgCmds[$icmd++] = [ @SysArgs ];
    }
  }

# Submit the jobs
&DiagUtils::SubmitParallelJobs(\@TsavgCmds, $Nprocs, "tsavg");

exit 0;
