#!/usr/bin/env perl
#
# Script to run gen_xsection on a list of simulation cases
#

BEGIN { push(@INC, "$ENV{HOME}/etc/perl"); }

use strict;
use File::Basename;
use DiagUtils;

#######################################################################
# SUBROUTINES
#######################################################################

#######################################################################
# MAIN
#######################################################################

my $ConfigFile;
my $Nprocs;

my $Config;

my @CaseList;
my $Case;

my %XsectionJobs;
my $Xname;
my $InType;
my $LineSpec;
my @FileList;
my $FileSpec;
my $ifile;

my @XsectionCmds;
my $icmd;

my @SysArgs;
my $iarg;

my $ilog;
my $LogFile;
my $Pid;

if ($#ARGV != 1)
  {
  print "ERROR: must supply exactly two arguments\n";
  print "\n";
  print "USAGE: run_azavg <ConfigFile> <NumberProcesses>\n";
  exit -1;
  }

$ConfigFile = $ARGV[0];
$Nprocs = $ARGV[1];

print "Run azavg diagnostic jobs\n";
print "  Configuration file: $ConfigFile\n";
print "  Number of processes: $Nprocs\n";
print "\n";

# Read in info from the config file.
($Config) = &DiagUtils::ReadDiagConfigFile($ConfigFile);

# Walk through all cases and all azavg jobs and construct the
# corresponding list of azavg commands. 
#
# Divide the total number of azavg commands evenly by the 
# requested number of processes and run each subset in
# separate processes.

@CaseList = @{ $$Config{CASE_LIST} };
%XsectionJobs = %{ $$Config{XSECTION} };

foreach $Case (@CaseList)
  {
  foreach $Xname (sort(keys(%XsectionJobs)))
    {
    # Grab the job specs
    $InType   = $XsectionJobs{$Xname}{IN_TYPE};
    $LineSpec = $XsectionJobs{$Xname}{LINE_SPEC};
    @FileList = @{ $XsectionJobs{$Xname}{FILE_LIST} };

    $iarg = 0;
    undef @SysArgs;
    $SysArgs[$iarg++] = "gen_xsection"; 
    if (($InType eq "h_tan") || ($InType eq "h_rad"))
      {
      $SysArgs[$iarg++] = "-t";
      $SysArgs[$iarg++] = "$InType";
      }
    $SysArgs[$iarg++] = $LineSpec; 
    foreach $ifile (0 .. $#FileList)
      {
      $FileSpec = $FileList[$ifile];
      $FileSpec =~ s/<CASE>/$Case/g;
      $SysArgs[$iarg++] = $FileSpec;
      }

    # Add the command line to the main list
    $XsectionCmds[$icmd++] = [ @SysArgs ];
    }
  }

# Submit the jobs
&DiagUtils::SubmitParallelJobs(\@XsectionCmds, $Nprocs, "xsection");

exit 0;
