#!/usr/bin/env perl
#
# script to run grads to generate az avg data plots
#

BEGIN { push(@INC, "$ENV{HOME}/etc/perl"); }

use strict;
use DiagUtils;

###########################################################################
# SUBROUTINES
###########################################################################

###########################################################################
# MAIN
###########################################################################

my $Gvar;
my $Gfile;
my $TimeStep;
my $Ztop;
my $Ccols;
my $Clevs;
my $Ptitle;
my $Xtitle;
my $Ytitle;
my $Pfile;


$Gvar="speed_t";
$Gfile="AzAveragedData/speed_t_TC_SEED_C0100.ctl";

$TimeStep=7;
$Ccols="9 14 4 11 5 13 3 10 7 12 8 2 6";
$Clevs="10.0 15.0 20.0 25.0 30.0 35.0 40.0 45.0 50.0 55.0 60.0 65.0 70.0";
$Ztop=16000;

$Ptitle="TC42: AZ: spd_t (m/s), TC_SEED_C0100, t 48 hrs";
$Xtitle="Radius (km)";
$Ytitle="Height (m)";

$Pfile="plots/AzAveragedData/speed_t_TC_SEED_C0100_48.gif";

&DiagUtils::PlotGradsVslice($Gvar,$Gfile,$TimeStep,$Ztop,$Ccols,$Clevs,$Ptitle,$Xtitle,$Ytitle,$Pfile);

exit 0;
