#!/usr/bin/env bash
#
# script to create an animated gif file from a series of png files (frames)
#
#  1st arg is file name up to the numbering at the end.

Fprefix="$1"

FFMPEG_HOME="$HOME/ffmpeg/ffmpeg-3.3.3-install"

WorkDir=$(dirname $Fprefix)

# create a color palette customized to the colors used in the input png images
$FFMPEG_HOME/bin/ffmpeg -y -i "${Fprefix}_%04d.png" -vf scale=720:-1:flags=lanczos,palettegen ${WorkDir}/palette.png

# create the output gif using the custom color palette
#OutFile="${Fprefix}.gif"
OutFile="${Fprefix}.mp4"

# setpts filter will scale the animation speed
#    DelayFac < 1.0 slows down
#    DelayFac > 1.0 speeds up 
DelayFac=3.0
$FFMPEG_HOME/bin/ffmpeg -y -i "${Fprefix}_%04d.png" -i ${WorkDir}/palette.png -t 180 \
   -filter_complex "scale=720:-1:flags=lanczos[x];[x][1:v]paletteuse, setpts=${DelayFac}*PTS" $OutFile
