#!/usr/bin/env bash
#
# script to create figures for AIE - TC paper

Jsize="1200x900"

# Figure 1: RAMS grids
echo "Figure 1"
montage -tile 1x1 -geometry ${Jsize} RamsGrids.jpg Figure1.jpg

# Figure 2: Control sim
echo "Figure 2"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 InitVortex.jpg \
 AerosolProfiles.jpg \
 ControlVtSpl.jpg \
 Blank.jpg \
 Figure2.jpg

# Figure 3: KE-Vt above RMW
echo "Figure 3"
montage -tile 1x2 -geometry ${Jsize}+2+100 \
 KeVt.jpg \
 TS_rmw.jpg \
 Figure3.jpg

# Figure 4: EOF in first column, VintCond in second column
echo "Figure 4"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 EOF1_theta_e_TCS_SD_C2000.jpg \
 vint_cond_TCS_SD_C0100.jpg \
 Blank.jpg \
 vint_cond_TCS_SD_C2000.jpg \
 Figure4.jpg

## Figure 5: storm core: cloud num conc in first column, cloud mean diam in second column
#echo "Figure 5"
#montage -tile 2x2 -geometry ${Jsize}+2+100 \
# pts_cloud_cm3_SC_LC_TCS_SD_C0100.jpg \
# pts_cloud_d_SC_LC_TCS_SD_C0100.jpg \
# pts_cloud_cm3_SC_LC_TCS_SD_C2000.jpg \
# pts_cloud_d_SC_LC_TCS_SD_C2000.jpg \
# Figure5.jpg

# Figure 5: storm core: cloud num conc in first column, cloud mean diam in second column
echo "Figure 5"
montage -tile 1x2 -geometry ${Jsize}+2+100 \
 pts_cloud_cm3_diff_SC_LC_TCS_SD_C2000.jpg \
 pts_cloud_d_diff_SC_LC_TCS_SD_C2000.jpg \
 Figure5.jpg

# Figure 6: storm core: latent heat in first column, w in second column
echo "Figure 6"
montage -tile 2x3 -geometry ${Jsize}+2+100 \
 prs_lh_tott_diff_SC_SS_TCS_SD_C2000.jpg \
 prs_w_diff_SC_SS_TCS_SD_C2000.jpg \
 prof_lh_tott_SC_SS.jpg \
 prof_w_SC_SS.jpg \
 prof_lh_tott_diff_SC_SS.jpg \
 prof_w_diff_SC_SS.jpg \
 Figure6.jpg

# Figure 7: storm core: relative vorticity
echo "Figure 7"
montage -tile 1x3 -geometry ${Jsize}+2+100 \
 prs_relvortz_rvz1em4_SC_SS_TCS_SD_C0100.jpg \
 prs_relvortz_rvz1em4_SC_SS_TCS_SD_C2000.jpg \
 prs_relvortz_rvz1em4_diff_SC_SS_TCS_SD_C2000.jpg \
 Figure7.jpg

# Figure 8: rainbands, profiles
echo "Figure 8"
montage -tile 1x3 -geometry ${Jsize}+2+100 \
 prof_theta_e_diff_RB_SS.jpg \
 prof_w_diff_RB_SS.jpg \
 TS_DeltapAll_SC_RB.jpg \
 Figure8.jpg

# Figure 9: compare core and rainbands, dynamic response
echo "Figure 9"
montage -tile 1x2 -geometry ${Jsize}+2+100 \
 pts_w_diff_SC_LC_TCS_SD_C2000.jpg \
 pts_w_diff_RB_LC_TCS_SD_C2000.jpg \
 Figure9.jpg

# Figure 10: destructive potential
echo "Figure 10"
montage -tile 1x1 -geometry ${Jsize} \
 R_Vt_All_SS_ext.jpg \
 Figure10.jpg

# Figure 11: schematic
echo "Figure 11"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 Slide1.jpg \
 Slide2.jpg \
 Blank.jpg \
 Slide3.jpg \
 Figure11.jpg
