#!/usr/bin/env bash
#
# script to create figures for ATEX paper

Jsize="1200x900"

echo "Figure: Storm Evolution"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 TsDebbyTracks.jpg \
 TsDebbyPress.jpg \
 HovVintCond.jpg \
 FigureStormEvolution.jpg

echo "Figure: Storm Winds"
montage -tile 3x3 -geometry ${Jsize}+2+100 \
 WindsStream_T42.jpg \
 PrecipRate_T42.jpg \
 WindsVt_T42.jpg \
 WindsStream_T66.jpg \
 PrecipRate_T66.jpg \
 WindsVt_T66.jpg \
 WindsStream_T90.jpg \
 PrecipRate_T90.jpg \
 WindsVt_T90.jpg \
 FigureStormWinds.jpg

