#!/usr/bin/env bash
#
# script to create animated gif files for NASA Wisc project

SimList="RCE_3km_1mom RCE_3km_2mom RCE_3km_2mom_db RCE_3km_2mom_dm"

VarList="Prate Tcond"

for Sim in $SimList
do
  echo "************* Creating animated gif for simulation: $Sim *************"
  echo

  for Var in $VarList
  do
    echo "Variable: $Var ===================================="
    echo

    Fprefix="Animations/${Sim}/${Var}/${Var}_${Sim}"
    make_anim_gif $Fprefix
    echo
  done
done

