#
# Config
#

DEST = $(HOME)/bin
SCRIPTS = $(DEST)/lp1 \
          $(DEST)/lp2 \
          $(DEST)/grads2vis5d \
          $(DEST)/run_g2v \
          $(DEST)/run_vapor \
          $(DEST)/gen_html_index \
          $(DEST)/unpack_src_archive

#
# Targets
#

all: $(SCRIPTS)

$(DEST)/lp1: lp1
	cp lp1 $(DEST)/lp1

$(DEST)/lp2: lp2
	cp lp2 $(DEST)/lp2

$(DEST)/grads2vis5d: grads2vis5d
	cp grads2vis5d $(DEST)/grads2vis5d

$(DEST)/run_g2v: run_g2v
	cp run_g2v $(DEST)/run_g2v

$(DEST)/run_vapor: run_vapor
	cp run_vapor $(DEST)/run_vapor

$(DEST)/gen_html_index: gen_html_index
	cp gen_html_index $(DEST)/gen_html_index

$(DEST)/unpack_src_archive: unpack_src_archive
	cp unpack_src_archive $(DEST)/unpack_src_archive

