#!/usr/bin/env bash
#
# script to create figures for TC Workshop, May 2013 presentation

Jsize="1200x900"

# RAMS  grids
echo "Model Grids"
montage -tile 1x1 -geometry ${Jsize} \
 RamsGrids.jpg \
 FigModelGrids.jpg

# aerosol profile
echo "Aerosol Profile"
montage -tile 1x1 -geometry ${Jsize} \
 TCWS0513_AerosolProfiles.jpg \
 FigAeroProfiles.jpg

# Storm Development
echo "Storm Development"
montage -tile 2x1 -geometry ${Jsize}+2+100 \
 TCWS0513_KeVt_ext.jpg \
 TCWS0513_TS_rmw.jpg \
 FigStormDevel.jpg

# Vertically Integrated Condensate
echo "Vertically Integrated Condensate"
montage -tile 2x1 -geometry ${Jsize}+2+100 \
 TCWS0513_vint_cond_TCS_SD_C0100.jpg \
 TCWS0513_vint_cond_TCS_SD_C2000.jpg \
 FigVintCond.jpg

# Cloud Droplets
echo "Cloud Droplets"
montage -tile 2x1 -geometry ${Jsize}+2+100 \
 TCWS0513_pts_cloud_cm3_twp4_diff_SC_LC_TCS_SD_C2000.jpg \
 TCWS0513_pts_cloud_d_twp4_diff_SC_LC_TCS_SD_C2000.jpg \
 FigCloudDroplets.jpg

# Latent Heating
echo "Latent Heating"
montage -tile 2x1 -geometry ${Jsize}+2+100 \
 TCWS0513_prs_lh_tott_lht1p0_SC_SS_TCS_SD_C2000.jpg \
 TCWS0513_prof_lh_tott_lht1p0_diff_SC_SS.jpg \
 FigLatHeat.jpg

# Vertical Velocity
echo "Vertical Velocity"
montage -tile 2x1 -geometry ${Jsize}+2+100 \
 TCWS0513_prs_w_diff_SC_SS_TCS_SD_C2000.jpg \
 TCWS0513_prof_w_diff_SC_SS.jpg \
 FigVerticalVelocity.jpg

# Relative Vorticity
echo "Relative Vorticity"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 TCWS0513_prs_relvortz_rvz1em4_SC_SS_TCS_SD_C0100.jpg \
 Blank.jpg \
 TCWS0513_prs_relvortz_rvz1em4_SC_SS_TCS_SD_C2000.jpg \
 TCWS0513_prs_relvortz_rvz1em4_diff_SC_SS_TCS_SD_C2000.jpg \
 FigRelVorticity.jpg

# Schematic
echo "RB ThetaE Vertical Velocity"
 montage -tile 2x2 -geometry ${Jsize}+2+100 \
 TCWS0513_prof_theta_e_RB_SS.jpg \
 TCWS0513_prof_theta_e_diff_RB_SS.jpg \
 TCWS0513_prof_w_twp4_RB_SS.jpg \
 TCWS0513_prof_w_twp4_diff_RB_SS.jpg \
 FigThetaeVertVelocityRB.jpg

# Schematic
echo "Schematic"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 Slide1.jpg \
 Slide2.jpg \
 Blank.jpg \
 Slide3.jpg \
 FigSchematic.jpg

