#!/usr/bin/env bash
#
# script to create figures for AIE - TC paper

Jsize="1200x900"

# Figure 1: RAMS grids
echo "Figure 1"
montage -tile 1x1 -geometry ${Jsize} RamsGrids.jpg Figure1.jpg

# Figure 2: Control sim
echo "Figure 2"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 InitVortex.jpg \
 ControlVtSpl.jpg \
 AerosolProfiles.jpg \
 Blank.jpg \
 Figure2.jpg

# Figure 3: KE-Vt above RMW
echo "Figure 3"
montage -tile 1x2 -geometry ${Jsize} KeVt.jpg TS_rmw.jpg Figure3.jpg

# Figure 4: EOF in first column, VintCond in second column
echo "Figure 4"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 Blank.jpg \
 vint_cond_TCS_SD_C0100.jpg \
 EOF1_theta_e_TCS_SD_C2000.jpg \
 vint_cond_TCS_SD_C2000.jpg \
 Figure4.jpg

# Figure 5: storm core: cloud num conc in first column, cloud mean diam in second column
echo "Figure 5"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 pts_cloud_cm3_twp4_SC_LC_TCS_SD_C0100.jpg \
 pts_cloud_d_twp4_SC_LC_TCS_SD_C0100.jpg \
 pts_cloud_cm3_twp4_SC_LC_TCS_SD_C2000.jpg \
 pts_cloud_d_twp4_SC_LC_TCS_SD_C2000.jpg \
 Figure5.jpg

# Figure 6: storm core: latent heat in first column, w in second column
echo "Figure 6"
montage -tile 2x3 -geometry ${Jsize}+2+100 \
 prs_lh_tott_lht1p0_SC_SS_TCS_SD_C2000.jpg \
 prs_w_SC_SS_TCS_SD_C2000.jpg \
 prof_lh_tott_lht1p0_SC_SS.jpg \
 prof_w_SC_SS.jpg \
 prof_lh_tott_lht1p0_diff_SC_SS.jpg \
 prof_w_diff_SC_SS.jpg \
 Figure6.jpg

# Figure 7: storm core: relative vorticity
echo "Figure 7"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 prs_relvortz_rvz1em4_SC_SS_TCS_SD_C0100.jpg \
 Blank.jpg \
 prs_relvortz_rvz1em4_SC_SS_TCS_SD_C2000.jpg \
 prs_relvortz_rvz1em4_diff_SC_SS_TCS_SD_C2000.jpg \
 Figure7.jpg

# Figure 8: rainbands, profiles
echo "Figure 8"
montage -tile 2x3 -geometry ${Jsize}+2+100 \
 prof_speed_r_RB_SS.jpg \
 prof_speed_r_diff_RB_SS.jpg \
 prof_theta_e_RB_SS.jpg \
 prof_theta_e_diff_RB_SS.jpg \
 prof_w_twp4_RB_SS.jpg \
 prof_w_twp4_diff_RB_SS.jpg \
 Figure8.jpg

# Figure 9: pressure diff
echo "Figure 9"
montage -tile 1x1 -geometry ${Jsize}+2+100 \
  TS_DeltapAll_SC_RB.jpg \
  Figure9.jpg

# Figure 10: compare core and rainbands, dynamic response
echo "Figure 10"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 pts_w_SC_LC_TCS_SD_C0100.jpg \
 pts_w_RB_LC_TCS_SD_C0100.jpg \
 pts_w_SC_LC_TCS_SD_C2000.jpg \
 pts_w_RB_LC_TCS_SD_C2000.jpg \
 Figure10.jpg

# Figure 11: destructive potential
echo "Figure 11"
montage -tile 1x2 -geometry ${Jsize}+2+100 \
 KeVt_ext_annot.jpg \
 R_Vt_All_SS_ext.jpg \
 Figure11.jpg

# Figure 12: schematic
echo "Figure 12"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 Slide1.jpg \
 Slide2.jpg \
 Blank.jpg \
 Slide3.jpg \
 Figure12.jpg
