#
# Config
#

DEST = $(HOME)/etc/matlab
SCRIPTS = $(DEST)/GenHist2d.m \
          $(DEST)/GenRrateHist.m \
          $(DEST)/PlotHist2d.m \
          $(DEST)/PlotRrateHist.m \
          $(DEST)/ExtractSample.m \
          $(DEST)/MergeHists.m \
          $(DEST)/PlotHistSet.m \
          $(DEST)/PlotHists.m \
          $(DEST)/PlotSampleData.m \
          $(DEST)/PlotMultiPanelSample.m \
          $(DEST)/GenTimeSeries.m \
          $(DEST)/RatioAvg2d.m \
          $(DEST)/PlotTimeSeries.m \
          $(DEST)/PlotTseriesSet.m \


#
# Targets
#

all: $(SCRIPTS)

$(DEST)/GenHist2d.m: GenHist2d.m
	cp GenHist2d.m $(DEST)/GenHist2d.m

$(DEST)/GenRrateHist.m: GenRrateHist.m
	cp GenRrateHist.m $(DEST)/GenRrateHist.m

$(DEST)/PlotHist2d.m: PlotHist2d.m
	cp PlotHist2d.m $(DEST)/PlotHist2d.m

$(DEST)/PlotRrateHist.m: PlotRrateHist.m
	cp PlotRrateHist.m $(DEST)/PlotRrateHist.m

$(DEST)/ExtractSample.m: ExtractSample.m
	cp ExtractSample.m $(DEST)/ExtractSample.m

$(DEST)/MergeHists.m: MergeHists.m
	cp MergeHists.m $(DEST)/MergeHists.m

$(DEST)/PlotHistSet.m: PlotHistSet.m
	cp PlotHistSet.m $(DEST)/PlotHistSet.m

$(DEST)/PlotHists.m: PlotHists.m
	cp PlotHists.m $(DEST)/PlotHists.m

$(DEST)/PlotSampleData.m: PlotSampleData.m
	cp PlotSampleData.m $(DEST)/PlotSampleData.m

$(DEST)/PlotMultiPanelSample.m: PlotMultiPanelSample.m
	cp PlotMultiPanelSample.m $(DEST)/PlotMultiPanelSample.m

$(DEST)/GenTimeSeries.m: GenTimeSeries.m
	cp GenTimeSeries.m $(DEST)/GenTimeSeries.m

$(DEST)/RatioAvg2d.m: RatioAvg2d.m
	cp RatioAvg2d.m $(DEST)/RatioAvg2d.m

$(DEST)/PlotTimeSeries.m: PlotTimeSeries.m
	cp PlotTimeSeries.m $(DEST)/PlotTimeSeries.m

$(DEST)/PlotTseriesSet.m: PlotTseriesSet.m
	cp PlotTseriesSet.m $(DEST)/PlotTseriesSet.m

