#!/usr/bin/env bash
#
# script to create an animated gif file from a series of png files (frames)
#
#  1st arg is file name up to the numbering at the end.

Fprefix="$1"

FFMPEG_HOME="$HOME/ffmpeg/ffmpeg-3.3.3-install"

WorkDir=$(dirname $Fprefix)

# create a color palette customized to the colors used in the input png images
$FFMPEG_HOME/bin/ffmpeg -y -i "${Fprefix}_%04d.png" -vf scale=720:-1:flags=lanczos,palettegen ${WorkDir}/palette.png

# create the output gif using the custom color palette
$FFMPEG_HOME/bin/ffmpeg -y -i "${Fprefix}_%04d.png" -i ${WorkDir}/palette.png -t 60 \
   -filter_complex "scale=720:-1:flags=lanczos[x];[x][1:v]paletteuse" ${Fprefix}.gif
