#!/usr/bin/env bash
#
# script to create figures for ATEX paper

Jsize="1200x900"

echo "Figure 1: ATEX sounding"
montage -tile 1x1 -geometry ${Jsize}+2+100 \
 InitialSounding.jpg \
 Figure1.jpg

echo "Figure 2: Aerosol profiles"
montage -tile 1x2 -geometry ${Jsize}+2+100 \
 InitialCcnProfile.jpg \
 InitialGccnProfile.jpg \
 Figure2.jpg

echo "Figure 3: Bar graphs, CF and ACC_PCP, CCN only"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 cf_avg_bars.jpg \
 acc_pcp_bars.jpg \
 cd_avg_bars.jpg \
 pcprr_avg_bars.jpg \
 Figure3.jpg

echo "Figure 4: Cloud Frac, Cloud, PCPRR, CCN only"
montage -tile 3x3 -geometry ${Jsize}+2+100 \
 Cloud_T12_T36_CO_S293_G10M5_ALL.jpg \
 copt_thick_pdf_S293.jpg \
 pcprr_pdf_S293.jpg \
 Cloud_T12_T36_CO_S298_G10M5_ALL.jpg \
 copt_thick_pdf_S298.jpg \
 pcprr_pdf_S298.jpg \
 Cloud_T12_T36_CO_S303_G10M5_ALL.jpg \
 copt_thick_pdf_S303.jpg \
 pcprr_pdf_S303.jpg \
 Figure4.jpg

echo "Figure 5: BuoyFlux, Wvar, Wskew, CCN only"
montage -tile 3x3 -geometry ${Jsize}+2+100 \
 BuoyFlux_T12_T36_CO_S293_G10M5_ALL.jpg \
 Wvar_T12_T36_CO_S293_G10M5_ALL.jpg \
 Wskew_T12_T36_CO_S293_G10M5_ALL.jpg \
 BuoyFlux_T12_T36_CO_S298_G10M5_ALL.jpg \
 Wvar_T12_T36_CO_S298_G10M5_ALL.jpg \
 Wskew_T12_T36_CO_S298_G10M5_ALL.jpg \
 BuoyFlux_T12_T36_CO_S303_G10M5_ALL.jpg \
 Wvar_T12_T36_CO_S303_G10M5_ALL.jpg \
 Wskew_T12_T36_CO_S303_G10M5_ALL.jpg \
 Figure5.jpg

echo "Figure 6: Bar graphs, CF and ACC_PCP, CCN and GCCN"
montage -tile 2x2 -geometry ${Jsize}+2+100 \
 cf_avg_bars_gccn.jpg \
 acc_pcp_bars_gccn.jpg \
 cd_avg_bars_gccn.jpg \
 pcprr_avg_bars_gccn.jpg \
 Figure6.jpg

echo "Figure 7: Cloud Frac, Cloud, PCPRR, CCN and GCCN"
montage -tile 3x3 -geometry ${Jsize}+2+100 \
 Cloud_T12_T36_CG_C50_S298.jpg \
 copt_thick_pdf_C50_S298.jpg \
 pcprr_pdf_C50_S298.jpg \
 Cloud_T12_T36_CG_C400_S298.jpg \
 copt_thick_pdf_C400_S298.jpg \
 pcprr_pdf_C400_S298.jpg \
 Cloud_T12_T36_CG_C1600_S298.jpg \
 copt_thick_pdf_C1600_S298.jpg \
 pcprr_pdf_C1600_S298.jpg \
 Figure7.jpg

echo "Figure 8: BuoyFlux, Wvar, Wskew, CCN and GCCN"
montage -tile 3x3 -geometry ${Jsize}+2+100 \
 BuoyFlux_T12_T36_CG_C50_S298.jpg \
 Wvar_T12_T36_CG_C50_S298.jpg \
 Wskew_T12_T36_CG_C50_S298.jpg \
 BuoyFlux_T12_T36_CG_C400_S298.jpg \
 Wvar_T12_T36_CG_C400_S298.jpg \
 Wskew_T12_T36_CG_C400_S298.jpg \
 BuoyFlux_T12_T36_CG_C1600_S298.jpg \
 Wvar_T12_T36_CG_C1600_S298.jpg \
 Wskew_T12_T36_CG_C1600_S298.jpg \
 Figure8.jpg

echo "Figure 9: Albedo, sfc conv examples, C50, S293 CCN only"
montage -tile 3x2 -geometry ${Jsize}+2+100 \
 Albedo_T12_z.atex.ccn0050.sst293.gcn10m5.1um.jpg \
 Albedo_T24_z.atex.ccn0050.sst293.gcn10m5.1um.jpg \
 Albedo_T36_z.atex.ccn0050.sst293.gcn10m5.1um.jpg \
 SfcDiv_T12_z.atex.ccn0050.sst293.gcn10m5.1um.jpg \
 SfcDiv_T24_z.atex.ccn0050.sst293.gcn10m5.1um.jpg \
 SfcDiv_T36_z.atex.ccn0050.sst293.gcn10m5.1um.jpg \
 Figure9.jpg

echo "Figure 10: Albedo, sfc conv examples, C1600, S303 CCN only"
montage -tile 3x2 -geometry ${Jsize}+2+100 \
 Albedo_T12_z.atex.ccn1600.sst303.gcn10m5.1um.jpg \
 Albedo_T24_z.atex.ccn1600.sst303.gcn10m5.1um.jpg \
 Albedo_T36_z.atex.ccn1600.sst303.gcn10m5.1um.jpg \
 SfcDiv_T12_z.atex.ccn1600.sst303.gcn10m5.1um.jpg \
 SfcDiv_T24_z.atex.ccn1600.sst303.gcn10m5.1um.jpg \
 SfcDiv_T36_z.atex.ccn1600.sst303.gcn10m5.1um.jpg \
 Figure10.jpg

### echo "Figure 4: Time snapshots albedo and sfc convergence S293, C400, CCN only"
### montage -tile 3x2 -geometry ${Jsize}+2+100 \
###  Albedo_T12_z.atex.ccn0400.sst293.gcn10m5.1um.jpg \
###  Albedo_T24_z.atex.ccn0400.sst293.gcn10m5.1um.jpg \
###  Albedo_T36_z.atex.ccn0400.sst293.gcn10m5.1um.jpg \
###  SfcConv_T12_z.atex.ccn0400.sst293.gcn10m5.1um.jpg \
###  SfcConv_T24_z.atex.ccn0400.sst293.gcn10m5.1um.jpg \
###  SfcConv_T36_z.atex.ccn0400.sst293.gcn10m5.1um.jpg \
###  Figure4.jpg
### 
### echo "Figure 5: Time snapshots albedo and sfc convergence S298, C400, CCN only"
### montage -tile 3x2 -geometry ${Jsize}+2+100 \
###  Albedo_T12_z.atex.ccn0400.sst298.gcn10m5.1um.jpg \
###  Albedo_T24_z.atex.ccn0400.sst298.gcn10m5.1um.jpg \
###  Albedo_T36_z.atex.ccn0400.sst298.gcn10m5.1um.jpg \
###  SfcConv_T12_z.atex.ccn0400.sst298.gcn10m5.1um.jpg \
###  SfcConv_T24_z.atex.ccn0400.sst298.gcn10m5.1um.jpg \
###  SfcConv_T36_z.atex.ccn0400.sst298.gcn10m5.1um.jpg \
###  Figure5.jpg
### 
### echo "Figure 6: Time snapshots albedo and sfc convergence S303, C400, CCN only"
### montage -tile 3x2 -geometry ${Jsize}+2+100 \
###  Albedo_T12_z.atex.ccn0400.sst303.gcn10m5.1um.jpg \
###  Albedo_T24_z.atex.ccn0400.sst303.gcn10m5.1um.jpg \
###  Albedo_T36_z.atex.ccn0400.sst303.gcn10m5.1um.jpg \
###  SfcConv_T12_z.atex.ccn0400.sst303.gcn10m5.1um.jpg \
###  SfcConv_T24_z.atex.ccn0400.sst303.gcn10m5.1um.jpg \
###  SfcConv_T36_z.atex.ccn0400.sst303.gcn10m5.1um.jpg \
###  Figure6.jpg
### 
### echo "Figure 7: Time snapshots albedo and sfc convergence S298, C50, CCN only"
### montage -tile 3x2 -geometry ${Jsize}+2+100 \
###  Albedo_T12_z.atex.ccn0050.sst298.gcn10m5.1um.jpg \
###  Albedo_T24_z.atex.ccn0050.sst298.gcn10m5.1um.jpg \
###  Albedo_T36_z.atex.ccn0050.sst298.gcn10m5.1um.jpg \
###  SfcConv_T12_z.atex.ccn0050.sst298.gcn10m5.1um.jpg \
###  SfcConv_T24_z.atex.ccn0050.sst298.gcn10m5.1um.jpg \
###  SfcConv_T36_z.atex.ccn0050.sst298.gcn10m5.1um.jpg \
###  Figure7.jpg
### 
### echo "Figure 8: Time snapshots albedo and sfc convergence S298, C1600, CCN only"
### montage -tile 3x2 -geometry ${Jsize}+2+100 \
###  Albedo_T12_z.atex.ccn1600.sst298.gcn10m5.1um.jpg \
###  Albedo_T24_z.atex.ccn1600.sst298.gcn10m5.1um.jpg \
###  Albedo_T36_z.atex.ccn1600.sst298.gcn10m5.1um.jpg \
###  SfcConv_T12_z.atex.ccn1600.sst298.gcn10m5.1um.jpg \
###  SfcConv_T24_z.atex.ccn1600.sst298.gcn10m5.1um.jpg \
###  SfcConv_T36_z.atex.ccn1600.sst298.gcn10m5.1um.jpg \
###  Figure8.jpg
